---
- name: Kickstart Bastion Host with packer.io
  hosts: all
  vars_files:
    - vars/vars.yaml
  gather_facts: no
  roles:
    - bind
    - chrony
    - tftp
    - certs
    - nginx
    - cockpit
    - libvirt
    - mirror-centos
